# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 18:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='uploaded_ts',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
