# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paster', '0002_uploadimage_uploaded_ts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='picture_set',
        ),
    ]
